version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "18:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  reviewers:
  - quittle
  assignees:
  - quittle
  labels:
  - dependencies
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.23.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.22
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.24.2
    - 5.29.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.16.0
    - 4.20.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.2
    - 26.5.4
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.16.0
    - 4.20.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.31
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.17
    - 8.1.0
  - dependency-name: "@types/minimatch"
    versions:
    - 3.0.4
  - dependency-name: aws-sdk
    versions:
    - 2.834.0
    - 2.853.0
    - 2.878.0
