version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: monthly
          time: "18:00"
          timezone: America/New_York
      open-pull-requests-limit: 99
      reviewers:
          - quittle
      assignees:
          - quittle
      labels:
          - dependencies
