AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Parameters:
    LayerName:
        Type: String
        Description: The name of the Lambda Layer.
Resources:
    S3UploadCustomResourceLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: !Ref LayerName
            CompatibleRuntimes: [nodejs22.x]
            ContentUri: dist/layer.zip
            LicenseInfo: Apache-2.0
    S3UploadCustomResourceLayerPermission:
        Type: AWS::Lambda::LayerVersionPermission
        Properties:
            Action: lambda:GetLayerVersion
            LayerVersionArn: !Ref S3UploadCustomResourceLayer
            Principal: "*"
Outputs:
    LayerArn:
        Description: ARN of the Lambda Layer for other to consume
        Value: !Ref S3UploadCustomResourceLayer
