on:
    pull_request:
    push:
        branches:
            - main
        tags: v*

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            # The AWS JS SDK only respects AWS_REGION, not AWS_DEFAULT_REGION
            # See https://github.com/aws/aws-sdk-js/issues/2929
            AWS_DEFAULT_REGION: us-east-1
            AWS_REGION: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: APT Install
              run: |
                  sudo apt-get install \
                    jq \
                    python3-pip \
                    python3-setuptools
            - name: PIP Install
              run: |
                  pip3 install awscli --upgrade --user
            - name: NVM Install
              run: |
                  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
                  . $HOME/.nvm/nvm.sh
                  nvm install
            - name: NPM Install
              run: npm ci
            - name: Build and Test
              run: npm run build-and-test
            - name: Release
              if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
              run: npm run release
            - name: GitHub Release
              if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
              uses: ncipollo/release-action@v1
              with:
                  artifacts: dist/layer.zip
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: NPM Publish
              if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npm version from-git
                  npm publish --registry=https://registry.npmjs.org
